// source: signaling.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.signaling.StreamResponse');
goog.provide('proto.signaling.StreamResponse.EventCase');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.signaling.Leave');
goog.require('proto.signaling.Login');
goog.require('proto.signaling.Message');
goog.require('proto.signaling.Shutdown');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.signaling.StreamResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.signaling.StreamResponse.oneofGroups_);
};
goog.inherits(proto.signaling.StreamResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.signaling.StreamResponse.displayName = 'proto.signaling.StreamResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.signaling.StreamResponse.oneofGroups_ = [[1,2,3,4]];

/**
 * @enum {number}
 */
proto.signaling.StreamResponse.EventCase = {
  EVENT_NOT_SET: 0,
  LOGIN: 1,
  LEAVE: 2,
  MESSAGE: 3,
  SHUTDOWN: 4
};

/**
 * @return {proto.signaling.StreamResponse.EventCase}
 */
proto.signaling.StreamResponse.prototype.getEventCase = function() {
  return /** @type {proto.signaling.StreamResponse.EventCase} */(jspb.Message.computeOneofCase(this, proto.signaling.StreamResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.signaling.StreamResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.signaling.StreamResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.signaling.StreamResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.StreamResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    login: (f = msg.getLogin()) && proto.signaling.Login.toObject(includeInstance, f),
    leave: (f = msg.getLeave()) && proto.signaling.Leave.toObject(includeInstance, f),
    message: (f = msg.getMessage()) && proto.signaling.Message.toObject(includeInstance, f),
    shutdown: (f = msg.getShutdown()) && proto.signaling.Shutdown.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.signaling.StreamResponse}
 */
proto.signaling.StreamResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.signaling.StreamResponse;
  return proto.signaling.StreamResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.signaling.StreamResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.signaling.StreamResponse}
 */
proto.signaling.StreamResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.signaling.Login;
      reader.readMessage(value,proto.signaling.Login.deserializeBinaryFromReader);
      msg.setLogin(value);
      break;
    case 2:
      var value = new proto.signaling.Leave;
      reader.readMessage(value,proto.signaling.Leave.deserializeBinaryFromReader);
      msg.setLeave(value);
      break;
    case 3:
      var value = new proto.signaling.Message;
      reader.readMessage(value,proto.signaling.Message.deserializeBinaryFromReader);
      msg.setMessage(value);
      break;
    case 4:
      var value = new proto.signaling.Shutdown;
      reader.readMessage(value,proto.signaling.Shutdown.deserializeBinaryFromReader);
      msg.setShutdown(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.signaling.StreamResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.signaling.StreamResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.signaling.StreamResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.signaling.StreamResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLogin();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.signaling.Login.serializeBinaryToWriter
    );
  }
  f = message.getLeave();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.signaling.Leave.serializeBinaryToWriter
    );
  }
  f = message.getMessage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.signaling.Message.serializeBinaryToWriter
    );
  }
  f = message.getShutdown();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.signaling.Shutdown.serializeBinaryToWriter
    );
  }
};


/**
 * optional Login login = 1;
 * @return {?proto.signaling.Login}
 */
proto.signaling.StreamResponse.prototype.getLogin = function() {
  return /** @type{?proto.signaling.Login} */ (
    jspb.Message.getWrapperField(this, proto.signaling.Login, 1));
};


/**
 * @param {?proto.signaling.Login|undefined} value
 * @return {!proto.signaling.StreamResponse} returns this
*/
proto.signaling.StreamResponse.prototype.setLogin = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.signaling.StreamResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.StreamResponse} returns this
 */
proto.signaling.StreamResponse.prototype.clearLogin = function() {
  return this.setLogin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.StreamResponse.prototype.hasLogin = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Leave leave = 2;
 * @return {?proto.signaling.Leave}
 */
proto.signaling.StreamResponse.prototype.getLeave = function() {
  return /** @type{?proto.signaling.Leave} */ (
    jspb.Message.getWrapperField(this, proto.signaling.Leave, 2));
};


/**
 * @param {?proto.signaling.Leave|undefined} value
 * @return {!proto.signaling.StreamResponse} returns this
*/
proto.signaling.StreamResponse.prototype.setLeave = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.signaling.StreamResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.StreamResponse} returns this
 */
proto.signaling.StreamResponse.prototype.clearLeave = function() {
  return this.setLeave(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.StreamResponse.prototype.hasLeave = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Message message = 3;
 * @return {?proto.signaling.Message}
 */
proto.signaling.StreamResponse.prototype.getMessage = function() {
  return /** @type{?proto.signaling.Message} */ (
    jspb.Message.getWrapperField(this, proto.signaling.Message, 3));
};


/**
 * @param {?proto.signaling.Message|undefined} value
 * @return {!proto.signaling.StreamResponse} returns this
*/
proto.signaling.StreamResponse.prototype.setMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.signaling.StreamResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.StreamResponse} returns this
 */
proto.signaling.StreamResponse.prototype.clearMessage = function() {
  return this.setMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.StreamResponse.prototype.hasMessage = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Shutdown shutdown = 4;
 * @return {?proto.signaling.Shutdown}
 */
proto.signaling.StreamResponse.prototype.getShutdown = function() {
  return /** @type{?proto.signaling.Shutdown} */ (
    jspb.Message.getWrapperField(this, proto.signaling.Shutdown, 4));
};


/**
 * @param {?proto.signaling.Shutdown|undefined} value
 * @return {!proto.signaling.StreamResponse} returns this
*/
proto.signaling.StreamResponse.prototype.setShutdown = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.signaling.StreamResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.signaling.StreamResponse} returns this
 */
proto.signaling.StreamResponse.prototype.clearShutdown = function() {
  return this.setShutdown(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.signaling.StreamResponse.prototype.hasShutdown = function() {
  return jspb.Message.getField(this, 4) != null;
};


